context:
  version: "1.0.2.dev"
  build_number: 0

package:
  name: ginger
  version: ${{ version }}

source:
  git: ../
  depth: 1 #current HEAD

build:
  number: ${{ build_number }}
  script:
    - git rev-parse HEAD > VERSION
    - make
    - mv VERSION bin/ginger-util/
    - mkdir -p $PREFIX/bin
    - mv bin/* $PREFIX/bin/

requirements:
  build:
    - git
    - make
#    - ${{ compiler('cxx') }}
    - gxx >=13.2.0
    - libgcc-ng 
  run:
    - perl 
    - python 
    - nextflow ==22.10
    - transdecoder 
    - matplotlib 
    - sra-tools
    - hisat2 ==2.2.1 
    - samtools ==1.17
    - stringtie ==2.1.7 
    - perl-carp
    - perl-pathtools
    - perl-data-dumper 
    - perl-findbin 
    - perl-storable 
    - perl-uri 
    - velvet ==1.2.10 
    - oases ==0.2.09 
    - trinity 
    - gmap 
    - gffread 
    - cd-hit ==4.8.1 
    - seqkit 
    - perl-exporter 
    - gffutils 
    - jellyfish 
    - salmon 
    - spaln 
    - sed 
    - gcc 
    - augustus==3.5.0 pl5321h816be78_2
    - snap 
    - perl-dbi 
    - perl-parallel-forkmanager 
    - _libgcc_mutex 
    - libstdcxx-ng 
    - ca-certificates 
    - python_abi 
    - libgcc-devel_linux-64 
    - ld_impl_linux-64 ==2.40 h41732ed_0
    - libgfortran4 
    - libgomp
    - libgfortran-ng 
    - _openmp_mutex 
    - libgcc-ng 
    - graphite2
    - xorg-recordproto
    - xorg-inputproto 
    - xorg-libxdmcp 
    - pthread-stubs
    - xorg-xproto 
    - xorg-kbproto 
    - xorg-renderproto
    - libdb 
    - libev 
    - c-ares 
    - libbrotlicommon ==1.1.0 hd590300_1
    - pcre 
    - gettext 
    - libexpat 
    - xorg-libxau 
    - xorg-xextproto 
    - keyutils
    - libuuid 
    - xorg-libice 
    - pixman 
    - libwebp-base 
    - libiconv 
    - icu 
    - jpeg 
    - giflib 
    - alsa-lib 
    - openssl 
    - libffi 
    - gmp 
    - metis ==5.1.0 h59595ed_1007
    - libsanitizer 
    - blis ==0.9.0 hd590300_1
    - openblas 
    - lp_solve ==5.5.2.5 h14c3975_1001
    - xz 
    - libdeflate 
    - tbb 
    - bzip2 
    - ncurses 
    - ossuuid ==1.6.2 hf484d3e_1000
    - libzlib 
    - expat 
    - libxcb 
    - xorg-fixesproto ==5.0 h7f98852_1002
    - xorg-libsm 
    - mpfr 
    - libblas 
    - libedit
    - readline
    - libssh2 
    - libnghttp2 
    - libpng 
    - tk 
    - zstd 
    - zlib 
    - brotli-bin ==1.1.0 hd590300_1
    - xorg-libx11 
    - liblapack 
    - libcblas 
    - krb5 
    - sqlite 
    - freetype 
    - boost-cpp 
    - libglib 
    - libxml2 
    - brotli 
    - xorg-libxrender 
    - xorg-libxext 
    - xorg-libxfixes 
    - suitesparse 
    - gsl 
    - libcurl 
    - fontconfig 
    - openjpeg 
    - lcms2 
    - xorg-libxi 
    - curl 
    - xorg-libxtst 
    - wheel 
    - setuptools 
    - sysroot_linux-64 
    - pip 
    - olefile 
    - munkres 
    - zipp 
    - pyparsing 
    - cycler 
    - certifi 
    - packaging 
    - six 
    - argh 
    - argcomplete 
    - python-dateutil 
    - kmer-jellyfish ==2.3.0 h9f5acd7_3
    - perl-module-load 
    - perl-locale-maketext-simple 
    - perl-params-check 
    - perl-extutils-manifest 
    - perl-try-tiny 
    - perl-params-util 
    - perl-xml-sax-base 
    - perl-file-which 
    - perl-version 
    - perl-scalar-list-utils 
    - perl-lib 
    - perl-extutils-makemaker 
    - perl-sub-exporter-progressive 
    - perl-getopt-long 
    - perl-sub-identify 
    - perl-app-cpanminus 
    - perl-base 
    - perl-sub-name 
    - perl-mro-compat 
    - perl-module-runtime 
    - perl-sub-quote 
    - perl-class-method-modifiers 
    - perl-xsloader 
    - perl-parent 
    - perl-constant 
    - htslib ==1.17
    - bowtie2 
    - bowtie 
    - perl-module-corelist 
    - perl-text-parsewords 
    - perl-devel-globaldestruction 
    - perl-package-stash-xs 
    - perl-mime-base64 
    - perl-xml-namespacesupport 
    - perl-text-abbrev 
    - perl-perl-ostype 
    - perl-file-util 
    - perl-file-path 
    - perl-encode 
    - perl-module-metadata 
    - perl-cpan-meta-requirements 
    - perl-cpan-meta-yaml 
    - perl-eval-closure 
    - perl-sub-install 
    - perl-module-implementation 
    - perl-dist-checkconflicts 
    - perl-file-temp 
    - perl-business-isbn-data 
    - perl-module-load-conditional 
    - perl-data-optlist 
    - perl-module-runtime-conflicts 
    - perl-business-isbn 
    - perl-apache-test 
    - perl-ipc-cmd 
    - perl-sub-exporter 
    - perl-package-stash 
    - perl-extutils-cbuilder 
    - perl-class-load 
    - perl-package-deprecationmanager 
    - perl-devel-overloadinfo 
    - perl-extutils-parsexs 
    - perl-class-load-xs 
    - perl-json-pp 
    - perl-devel-stacktrace 
    - perl-yaml 
    - pyvcf3 
    - perl-role-tiny 
    - perl-xml-sax 
    - binutils_impl_linux-64 ==2.40 hf600244_0
    - unicodedata2 
    - sip 
    - glib 
    - tornado ==6.2 
    - numpy ==1.21.6 
    - simplejson ==3.17.6
    - pillow 
    - importlib-metadata 
    - kiwisolver ==1.4.4
    - gcc_impl_linux-64 ==13.2.0 h338b0a0_2
    - fonttools 
    - dbus ==1.13.6 hfdff14a_1
    - gstreamer 
    - cairo
    - boost ==1.74
    - biopython 
    - matplotlib-base 
    - gst-plugins-base 
    - harfbuzz 
    - openjdk 
    - perl-cpan-meta 
    - perl-moose 
    - perl-xml-libxml 
    - perl-module-build 
    - perl-moo 
    - ncbi-vdb ==3.0.8 hdbdd923_0
    - pyfaidx 
    - trimmomatic ==0.39 hdfd78af_2

about:
  homepage: https://github.com/i10labtitech/GINGER
  license: GPL-2.0-or-later
  summary: Gradual INtegrated GEne Reconstruction (GINGER)
  description: GINGER is a tool that is implemented an integrated method for gene structure prediction in higher eukaryotes. RNA-Seq-based methods, ab initio-based methods, homology-based methods are performed, and then gene structures are reconstructed via dynamic programming with appropriately weighted and scored exon/intron/intergenic regions. Different prediction processes and filtering criteria are applied to multi-exon and single-exon genes. This pipeline is implemented using Nextflow.
